volumes:
  grafana-data:

services:

  grafana:
    image: grafana/grafana-oss:9.4.3
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./big-server/config/prometheus.yml:/etc/prometheus/prometheus.yml

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    restart: on-failure
    ports:
      - "9308:9308"
    environment:
      KAFKA_URI: kafka:9092
    depends_on:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  server:
    build: server/
    command: python ./server.py
    depends_on:
      - kafka-exporter
#      - kafka-ui
      - kafka

  device1:
    build: device/
    command: python ./main.py 1
    depends_on:
      - server

  device2:
    build: device/
    command: python ./main.py 2
    depends_on:
      - server

  device3:
    build: device/
    command: python ./main.py 3
    depends_on:
      - server

  device4:
    build: device/
    command: python ./main.py 4
    depends_on:
      - server

  device5:
    build: device/
    command: python ./main.py 5
    depends_on:
      - server

  device6:
    build: device/
    command: python ./main.py 6
    depends_on:
      - server

  device7:
    build: device/
    command: python ./main.py 7
    depends_on:
      - server

  device8:
    build: device/
    command: python ./main.py 8
    depends_on:
      - server

  device9:
    build: device/
    command: python ./main.py 9
    depends_on:
      - server

  device10:
    build: device/
    command: python ./main.py 10
    depends_on:
      - server

  device11:
    build: device/
    command: python ./main.py 11
    depends_on:
      - server

  device12:
    build: device/
    command: python ./main.py 12
    depends_on:
      - server

  device13:
    build: device/
    command: python ./main.py 13
    depends_on:
      - server

  device14:
    build: device/
    command: python ./main.py 14
    depends_on:
      - server

  device15:
    build: device/
    command: python ./main.py 15
    depends_on:
      - server

  device16:
    build: device/
    command: python ./main.py 16
    depends_on:
      - server

  device17:
    build: device/
    command: python ./main.py 17
    depends_on:
      - server

  device18:
    build: device/
    command: python ./main.py 18
    depends_on:
      - server

  device19:
    build: device/
    command: python ./main.py 19
    depends_on:
      - server

  device20:
    build: device/
    command: python ./main.py 20
    depends_on:
      - server

  device21:
    build: device/
    command: python ./main.py 21
    depends_on:
      - server

  device22:
    build: device/
    command: python ./main.py 22
    depends_on:
      - server

  device23:
    build: device/
    command: python ./main.py 23
    depends_on:
      - server

  device24:
    build: device/
    command: python ./main.py 24
    depends_on:
      - server

  device25:
    build: device/
    command: python ./main.py 25
    depends_on:
      - server

  device26:
    build: device/
    command: python ./main.py 26
    depends_on:
      - server

  device27:
    build: device/
    command: python ./main.py 27
    depends_on:
      - server

  device28:
    build: device/
    command: python ./main.py 28
    depends_on:
      - server

  device29:
    build: device/
    command: python ./main.py 29
    depends_on:
      - server

  device30:
    build: device/
    command: python ./main.py 30
    depends_on:
      - server

  device31:
    build: device/
    command: python ./main.py 31
    depends_on:
      - server

  device32:
    build: device/
    command: python ./main.py 32
    depends_on:
      - server

  device33:
    build: device/
    command: python ./main.py 33
    depends_on:
      - server

  device34:
    build: device/
    command: python ./main.py 34
    depends_on:
      - server

  device35:
    build: device/
    command: python ./main.py 35
    depends_on:
      - server

  device36:
    build: device/
    command: python ./main.py 36
    depends_on:
      - server

  device37:
    build: device/
    command: python ./main.py 37
    depends_on:
      - server

  device38:
    build: device/
    command: python ./main.py 38
    depends_on:
      - server

  device39:
    build: device/
    command: python ./main.py 39
    depends_on:
      - server

  device40:
    build: device/
    command: python ./main.py 40
    depends_on:
      - server

  device41:
    build: device/
    command: python ./main.py 41
    depends_on:
      - server

  device42:
    build: device/
    command: python ./main.py 42
    depends_on:
      - server

  device43:
    build: device/
    command: python ./main.py 43
    depends_on:
      - server

  device44:
    build: device/
    command: python ./main.py 44
    depends_on:
      - server

  device45:
    build: device/
    command: python ./main.py 45
    depends_on:
      - server

  device46:
    build: device/
    command: python ./main.py 46
    depends_on:
      - server

  device47:
    build: device/
    command: python ./main.py 47
    depends_on:
      - server

  device48:
    build: device/
    command: python ./main.py 48
    depends_on:
      - server

  device49:
    build: device/
    command: python ./main.py 49
    depends_on:
      - server

  device50:
    build: device/
    command: python ./main.py 50
    depends_on:
      - server

  device51:
    build: device/
    command: python ./main.py 51
    depends_on:
      - server

  device52:
    build: device/
    command: python ./main.py 52
    depends_on:
      - server

  device53:
    build: device/
    command: python ./main.py 53
    depends_on:
      - server

  device54:
    build: device/
    command: python ./main.py 54
    depends_on:
      - server

  device55:
    build: device/
    command: python ./main.py 55
    depends_on:
      - server

  device56:
    build: device/
    command: python ./main.py 56
    depends_on:
      - server

  device57:
    build: device/
    command: python ./main.py 57
    depends_on:
      - server

  device58:
    build: device/
    command: python ./main.py 58
    depends_on:
      - server

  device59:
    build: device/
    command: python ./main.py 59
    depends_on:
      - server

  device60:
    build: device/
    command: python ./main.py 60
    depends_on:
      - server

  device61:
    build: device/
    command: python ./main.py 61
    depends_on:
      - server

  device62:
    build: device/
    command: python ./main.py 62
    depends_on:
      - server

  device63:
    build: device/
    command: python ./main.py 63
    depends_on:
      - server

  device64:
    build: device/
    command: python ./main.py 64
    depends_on:
      - server

  device65:
    build: device/
    command: python ./main.py 65
    depends_on:
      - server

  device66:
    build: device/
    command: python ./main.py 66
    depends_on:
      - server

  device67:
    build: device/
    command: python ./main.py 67
    depends_on:
      - server

  device68:
    build: device/
    command: python ./main.py 68
    depends_on:
      - server

  device69:
    build: device/
    command: python ./main.py 69
    depends_on:
      - server

  device70:
    build: device/
    command: python ./main.py 70
    depends_on:
      - server

  device71:
    build: device/
    command: python ./main.py 71
    depends_on:
      - server

  device72:
    build: device/
    command: python ./main.py 72
    depends_on:
      - server

  device73:
    build: device/
    command: python ./main.py 73
    depends_on:
      - server

  device74:
    build: device/
    command: python ./main.py 74
    depends_on:
      - server

  device75:
    build: device/
    command: python ./main.py 75
    depends_on:
      - server

  device76:
    build: device/
    command: python ./main.py 76
    depends_on:
      - server

  device77:
    build: device/
    command: python ./main.py 77
    depends_on:
      - server

  device78:
    build: device/
    command: python ./main.py 78
    depends_on:
      - server

  device79:
    build: device/
    command: python ./main.py 79
    depends_on:
      - server

  device80:
    build: device/
    command: python ./main.py 80
    depends_on:
      - server

  device81:
    build: device/
    command: python ./main.py 81
    depends_on:
      - server

  device82:
    build: device/
    command: python ./main.py 82
    depends_on:
      - server

  device83:
    build: device/
    command: python ./main.py 83
    depends_on:
      - server

  device84:
    build: device/
    command: python ./main.py 84
    depends_on:
      - server

  device85:
    build: device/
    command: python ./main.py 85
    depends_on:
      - server

  device86:
    build: device/
    command: python ./main.py 86
    depends_on:
      - server

  device87:
    build: device/
    command: python ./main.py 87
    depends_on:
      - server

  device88:
    build: device/
    command: python ./main.py 88
    depends_on:
      - server

  device89:
    build: device/
    command: python ./main.py 89
    depends_on:
      - server

  device90:
    build: device/
    command: python ./main.py 90
    depends_on:
      - server

  device91:
    build: device/
    command: python ./main.py 91
    depends_on:
      - server

  device92:
    build: device/
    command: python ./main.py 92
    depends_on:
      - server

  device93:
    build: device/
    command: python ./main.py 93
    depends_on:
      - server

  device94:
    build: device/
    command: python ./main.py 94
    depends_on:
      - server

  device95:
    build: device/
    command: python ./main.py 95
    depends_on:
      - server

  device96:
    build: device/
    command: python ./main.py 96
    depends_on:
      - server

  device97:
    build: device/
    command: python ./main.py 97
    depends_on:
      - server

  device98:
    build: device/
    command: python ./main.py 98
    depends_on:
      - server

  device99:
    build: device/
    command: python ./main.py 99
    depends_on:
      - server

  device100:
    build: device/
    command: python ./main.py 100
    depends_on:
      - server
