management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://92.118.148.71/docker-db
    username: root
    password: vVeLPxj7RZXttL7w
    driverClassName: org.postgresql.Driver